package scovmod.model.state.infection;

public enum InfectionState {
	UNDEFINED,  
	SUSCEPTIBLE, 
	EXPOSED_YOUNG,
	EXPOSED_ADULT,
	EXPOSED_ELDERLY,
	MILD_INFECTIOUS_YOUNG,
	MILD_INFECTIOUS_ADULT,
	MILD_INFECTIOUS_ELDERLY,
	SEVERE_INFECTIOUS_YOUNG,
	SEVERE_INFECTIOUS_ADULT,
	SEVERE_INFECTIOUS_ELDERLY,
	HOSPITALISED_YOUNG,
	HOSPITALISED_ADULT,
	HOSPITALISED_ELDERLY,
	RECOVERED_YOUNG,
	RECOVERED_ADULT,
	RECOVERED_ELDERLY,
	DEAD_YOUNG,
	DEAD_ADULT,
	DEAD_ELDERLY
}
